### ISSUE TITLE
Error when controlling night light

### ISSUE THREAD

**Issue by ifeign** [mikeleo/homebridge-litter-robot#2]
```
(node:24057) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/homebridge/node_modules/homebridge-litter-robot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-litter-robot/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-litter-robot/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:24057) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```
Night light worked for about 5 mins, then I started getting this error.

**Comment by ifeign** [comment]
Resolved this error by unplugging and replugging the litter box. This fixes the issue but does not explain the problem.
