### ISSUE TITLE
homebridge breaking bug

### ISSUE THREAD

**Issue by ifeign** [mikeleo/homebridge-litter-robot#4]
After an internet connection loss earlier today, I cannot get homebridge to run. Upon further investigation, I am getting this error repeatedly.

```
homebridge_1  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
homebridge_1  | (node:1894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2492)
homebridge_1  | (node:1894) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] /homebridge/cache/plugin-litter-robot/27f5e15b6af3223f1176293cd015771d does not look like a valid storage file!
homebridge_1  |     at /homebridge/node_modules/homebridge-litter-robot/node_modules/node-persist/src/local-storage.js:315:89
homebridge_1  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
homebridge_1  | (node:1894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2493)
homebridge_1  | (node:1894) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] /homebridge/cache/plugin-litter-robot/27f5e15b6af3223f1176293cd015771d does not look like a valid storage file!
homebridge_1  |     at /homebridge/node_modules/homebridge-litter-robot/node_modules/node-persist/src/local-storage.js:315:89
homebridge_1  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
homebridge_1  | (node:1894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2494)
homebridge_1  | (node:1894) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] /homebridge/cache/plugin-litter-robot/27f5e15b6af3223f1176293cd015771d does not look like a valid storage file!
homebridge_1  |     at /homebridge/node_modules/homebridge-litter-robot/node_modules/node-persist/src/local-storage.js:315:89
homebridge_1  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
homebridge_1  | (node:1894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2495)
homebridge_1  | (node:1894) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] /homebridge/cache/plugin-litter-robot/27f5e15b6af3223f1176293cd015771d does not look like a valid storage file!
```

**Comment by ifeign** [comment]
I’m no longer sure whether this issue caused homebridge to crash or if this is related to the text that my SD card was full due to an unrelated issue with Docker backups. What is apparent though is this error was generated for several hours and takes up the entire log until I uninstalled then reinstalled the plugin. My homebridge is back up and running and my space issue is fixed, but this still was concerning.

**Comment by apexad** [comment]
This does not look like an error caused by this plugin.
This issue should be closed.
