### ISSUE TITLE
v2 API?

### ISSUE THREAD

**Issue by canadaohcanada** [mikeleo/homebridge-litter-robot#7]
Howdy, my own inspection of the Litter-Robot app shows use of the https://v2.api.whisker.iothings.site/ url rather than the https://muvnkjeut7.execute-api.us-east-1.amazonaws.com URL this library uses. Is there a new API that needs to be looked into or has the URL simply changed to a different value? The results of the failed request call:

```
Starting Request { adapter: [Function: httpAdapter],
  transformRequest: { '0': [Function: transformRequest] },
  transformResponse: { '0': [Function: transformResponse] },
  timeout: 0,
  xsrfCookieName: 'XSRF-TOKEN',
  xsrfHeaderName: 'X-XSRF-TOKEN',
  maxContentLength: -1,
  validateStatus: [Function: validateStatus],
  headers:
   { common: { Accept: 'application/json, text/plain, */*' },
     delete: {},
     get: {},
     head: {},
     post: { 'Content-Type': 'application/x-www-form-urlencoded' },
     put: { 'Content-Type': 'application/x-www-form-urlencoded' },
     patch: { 'Content-Type': 'application/x-www-form-urlencoded' },
     'User-Agent':
      'Litter-Robot/1.0.5 (com.autopets.whisker.ios; build:29; iOS 12.1.2) Alamofire/4.5.1',
     'x-api-key': '....' },
  method: 'post',
  url:
   'https://muvnkjeut7.execute-api.us-east-1.amazonaws.com/staging/login',
  data:
   { oneSignalPlayerId: '0',
     password: '....,
     email: '....' } }
(node:3342) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/homebridge/node_modules/homebridge-litter-robot/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/homebridge/node_modules/homebridge-litter-robot/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-litter-robot/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:3342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by henry-swe** [comment]
same here

**Comment by itemduper** [comment]
Has anyone found a solution for this?  I've tried swapping URLs but no dice.

**Comment by itemduper** [comment]
I managed to answer my own question while digging into it.  There are not insignificant changes to the API.  It looks like another project for HomeAssistant (here: https://github.com/joshjcarrier/homeassistant-litter-robot/) has updated for the v2 API.  If I can make some time this weekend I'll try and isolate the changes and see if I can submit a patch.

**Comment by henry-swe** [comment]
I remembered when I tried to dig into it, the most significant change I found was the login credentials. It used to pass the password directly, but v2 seems to be using OAuth related stuff. Then I just gave up 😢

**Comment by mikeleo** [comment]
The API just kept working and so I did not update it.  The old API finally failed this past week and I took the plunge into figuring out the new v2 API.  It should be updated now and published.
